// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prztjpkuzhpovrpawwcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByenRqcGt1emhwb3ZycGF3d2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1MzA4MzEsImV4cCI6MjEwMDEwNjgzMX0.AfmLdXGf4SVDzPUcqMu8Aib0kT3H6GdbkPR6Avdz7IA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});